### ISSUE TITLE
OwnHub Tutorial

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/tutorials#1]
In this tutorial, we should show full life cycle of building a solution, sandboxing, creating its flist, uploading it to local hub and starting a container from that flist.

Depends on https://github.com/threefoldtech/jumpscaleX/issues/651

A person running this tutorial will provide the pre-provisioned zero-os. Make sure to point to tutorial on how to do that if missing. 

Example for web developers how to use gedis

- example html app with e.g. vue.js using the generated javascript client from gedis
- create example gedis + model
- show how to connect using python client
- show how to connect/use gedis using javascript in app
- show how to use vuejs which shows a form which is bound to the gedis client

**Comment by waleedhammam** [comment]
**Current Progress**
- own hub:
-- added option to install locally insystem or on a zos container
-- interactively shell untill you reach a ready ownhub container and running website
**TODO**
- Add an ownhub client to directly sandbox builders flists on it.
- Add an example for a builder life cycle -build, install, sandbox, start, stop- 
- Add a readme

**Comment by waleedhammam** [comment]
Done at: https://github.com/threefoldtech/tutorials/tree/master/tutorials/ownHub
The flow is:
![Untitled Diagram (3)](https://user-images.githubusercontent.com/10658229/60426823-b788cf00-9bf5-11e9-9afc-758d08e01dad.jpg)

**Comment by Dina-Abd-Elrahman** [comment]
### Verification steps:

- install tutorial
`
 jsx modules-install --url=https://github.com/threefoldtech/tutorials
`

- run Ownhub tutorail:
`
j.tutorials.ownhub.run()
` 

and follow the instructions .
