### ISSUE TITLE
Example for web developers how to use graphql with digital me server

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tutorials#2]
**Example for web developers how to use graphql with digital me server**

- Graphene as graphql server in python
- Apollo as graphql client: https://vue-apollo.netlify.com/guide/apollo/#apollo-options

**2 ways how it can be implemented on server** 

**1- Websockets (recommended)**
&nbsp;&nbsp;&nbsp;&nbsp; https://github.com/apollographql/subscriptions-transport-ws
&nbsp;&nbsp;&nbsp;&nbsp; https://github.com/graphql-python/graphql-ws
&nbsp;&nbsp;&nbsp;&nbsp;- Need websocket server on gevent
&nbsp;&nbsp;&nbsp;&nbsp;- Then terminate with Graphene

**2- PRO: it's the fastest & most efficient way (Using WSGI webserver)**
&nbsp;&nbsp;&nbsp;&nbsp;In gevent loop, use gevent simple webserver (WSGI)
&nbsp;&nbsp;&nbsp;&nbsp;http://www.gevent.org/api/gevent.pywsgi.html
&nbsp;&nbsp;&nbsp;&nbsp;http://mitsuhiko.pocoo.org/wzdoc/wsgihowto.html
&nbsp;&nbsp;&nbsp;&nbsp;Use http://mitsuhiko.pocoo.org/wzdoc/index.html for the low level handling of your web requests

Make example where we have the graphql next to the actor code so it's easy for people to see how to write the data management code and how to create actors
Use form example with vuejs, just some example form which does 2 way data binding to the backend graphql server (e.g. email change, name, description…)

**Info**
https://github.com/hasura/awesome-vue-graphql

**Comment by waleedhammam** [comment]
DigitalMe Actor: https://github.com/threefoldtech/digitalmeX/pull/271
Jumpscale Server: https://github.com/threefoldtech/jumpscaleX/commit/cbfd8f34fc57ff29168217c9fe1197e39ac54f39

**Comment by ranatrk** [comment]
Graphql builder: https://github.com/threefoldtech/jumpscaleX/commit/6b20ac4d44025e030f213a3ef3ea481ccb6f5de8

**Comment by waleedhammam** [comment]
Added tutorial on: https://github.com/threefoldtech/tutorials/tree/master/tutorials/gedis_graphql

**Comment by despiegk** [comment]
need better tutorial, 

- use grack
- show actor in link with graphql

check specs again

**Comment by ranatrk** [comment]
TODO:

- [x] tools in sal (for tutorial eg: printing)
- [x] move/update docs of graphql to include sanic
- [ ] adjust/enhance tutorial
- [ ]  use rack

**Comment by ranatrk** [comment]
Updates: 
https://github.com/threefoldtech/tutorials/commit/a004384bf1b66423f8dac727aaa83a0cc94bc7e5
https://github.com/threefoldtech/tutorials/commit/599cd3e366f3e9b7832b2e1485ce4b827bfa3f92
